In [5]:
#task2
import numpy as np

In [6]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b = M[0:2,0:2]
b

array([[1, 2],
       [5, 6]])

In [8]:
y = np.empty((M.shape))
y

array([[1.39441020e-311, 2.96439388e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.20953760e-312, 1.16095484e-028, 3.74168445e+233,
        3.10573437e-115],
       [2.85269821e-109, 2.59027926e-144, 4.82412328e+228,
        1.04718130e-142]])

In [9]:
z = np.array([1, 0, 1])
rzlt = np.empty_like(M) 
for number in range(4):
    rzlt[: ,number] = M[:,number] + z
rzlt

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
v = np.array([9,10])

In [11]:
A+B

array([[ 6,  8],
       [10, 12]])

In [12]:
A*B

array([[ 5, 12],
       [21, 32]])

In [13]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [14]:
np.dot(A, v)

array([29, 67])

In [15]:
for element in range(2):
    print(sum(A[:,element]))

4
6


In [18]:
B=np.array([[5,6],[7,8]])
B.transpose()
print(B)

[[5 6]
 [7 8]]
