In [2]:
#task2
import numpy as np

In [3]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
b = M[0:2,0:2]
b

array([[1, 2],
       [5, 6]])

In [5]:
y = np.empty((M.shape))
y

array([[8.01819371e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.76231868e+174, 4.75971510e-090,
        2.58141660e-057],
       [5.45022662e-067, 1.39939295e-076, 3.99910963e+252,
        1.46030983e-319]])

In [6]:
z = np.array([1, 0, 1])
rzlt = np.empty_like(M) 
for number in range(4):
    rzlt[: ,number] = M[:,number] + z
rzlt

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
v = np.array([9,10])

In [8]:
A+B

array([[ 6,  8],
       [10, 12]])

In [9]:
A*B

array([[ 5, 12],
       [21, 32]])

In [10]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [11]:
np.dot(A, v)

array([29, 67])

In [14]:
for element in range(2):
    print(sum(A[:,element]))

4
6


In [15]:
print(B.T)

[[5 7]
 [6 8]]
